config:
  title: Network Monitor
services:
- name: Maloja
  target: maloja.krateng.ch
  tests:
    port: 443
    https: 200
- name: Seafile
  target: seafile.krateng.ch
  tests:
    port: 443
    https: 200
- name: CDN
  target: cdn.krateng.ch
  tests:
    port: 443
    https: 200
- name: Minecraft
  target: minecraft.krateng.ch
  tests:
    port: 25565
machines:
- name: Constantinople
  desc: Main Router
  target_4: 192.168.178.1
- name: Rome
  desc: Basement Router
  target_4: 192.168.178.2
- name: Alexandria
  desc: Upstairs Router
  target_4: 192.168.178.3
- name: Krakow
  desc: Main Server
  target: krakow
- name: Antioch
  desc: DNS
  target: antioch
- name: Budapest
  desc: NAS
  target: budapest
